# Generated by Django 4.1.5 on 2023-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(
                    primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('online', models.ManyToManyField(
                    blank=True, related_name='rooms', to='chat.user')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
