# Generated by Django 4.1.5 on 2023-02-11 15:13

from django.db import migrations


class Migration(migrations.Migration):
    def room_lobby(apps, schema_editor):
        Room = apps.get_model('chat', 'Room')
        lobby = Room(name='lobby')
        lobby.save()

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(room_lobby),
    ]
